#! /usr/bin/env lua
local fmt = string.format

local item_template = "templates/rss-item.xml"

local feed_template = [[
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
   <channel>
      <title>Iago Leal</title>
      <link>https://iagoleal.com/</link>
      <description>Iago Leal's blog about math, programming and everything more.</description>
      <copyright>© Iago Leal de Freitas, 2020-2022</copyright>
      <language>en-us</language>
      <image>
        <url>https://iagoleal/static/img/me.jpg</url>
        <link>https://iagoleal.com/</link>
        <title>Iago Leal</title>
      </image>
      <managingEditor>hello@iagoleal.com</managingEditor>
      <webMaster>hello@iagoleal.com</webMaster>
      <docs>https://validator.w3.org/feed/docs/rss2.html</docs>
      %s
   </channel>
</rss>
]]

local function scandir(directory)
    local t = {}
    local file = io.popen(fmt("find '%s' -maxdepth 1 -type f", directory))
    for filename in file:lines() do
      table.insert(t, filename)
    end
    file:close()
    return t
end

local items = {}
for _, s in ipairs(scandir("content/posts")) do
  local aa   = fmt("pandoc --template=%s %s", item_template, s)
  local file = io.popen(aa)
  items[#items + 1] = file:read("*a")
  file:close()
end

local feed = fmt(feed_template, table.concat(items))

local fname = ...
local file = io.open(fname, "w+")
file:write(feed)
file:close()
