#!/usr/bin/env bash
DIR=$(dirname -- "$( realpath -- "$0")")

CACHEDIR=cache

if [ "$1" = "-" ]; then
  INFILE=/dev/stdin
else
  INFILE="$1"
fi
if [ "$2" = "-" ]; then
  OUTFILE=/dev/stdout
else
  OUTFILE="$2"
fi

TMPDIR="$(mktemp --directory --tmpdir tex2svg.XXXXXXXXXX)"

# FILE="${TMPDIR}/$(sha1sum "$INFILE" | awk '{print $1}')"
FILE="$TMPDIR/lalala"

cp "$INFILE" "${FILE}.tex"
# tex -> dvi
latex --output-format=dvi --halt-on-error --interaction nonstopmode --output-directory "$TMPDIR" "${FILE}.tex"
# dvi -> svg
dvisvgm --scale=2 --optimize=all --font-format=woff2 --exact -o "${FILE}.svg" "${FILE}.dvi"
# Generate output file
cp "${FILE}.svg" "$OUTFILE"
# $DIR/svg-minify "${FILE}.svg" "$OUTFILE"

## Currently unused
# pdftocairo -svg "${FILE}.pdf" "${FILE}.svg"
